# Generated by Django 4.0.6 on 2022-08-01 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_post_back_alter_post_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='back',
            field=models.ImageField(blank=True, upload_to='back/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.ImageField(blank=True, upload_to='cover/'),
        ),
    ]
